[package]
name = "patches-server"
version = "0.1.0"
authors = ["Emma Rose <emrose@mozilla.com>"]
edition = "2018"

[dependencies]
actix-redis = "^0.5"
actix-web = "^0.7"
redis-async = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
